-- Relative Path: lua/configs/all_the_icons.lua
--
-- This file centralizes all Nerd Font icons used throughout the configuration.
-- It allows other files (plugins, UI components) to require this single module
-- to access a consistent set of icons.

local icons = {}

-- Icons for AI tools
icons.ai = {
	bolt = "",
	chatgpt = "󰚩",
	claude = "󰙩",
	codeium = "󰘦",
	copilot = "",
	gemini = "󰠲",
	llama = "󱂷",
	mistral = "󱂵",
	openai = "󰡴",
	perplexity = "󰑣",
	robot = "ﮧ",
	supermaven = "",
	tabnine = "󰏚",
}

-- Icons for Cloud and DevOps
icons.cloud = {
	ansible = "󱁤",
	aws = "󰸏",
	azure = "",
	circuit_board = "",
	cloudflare = "󱂞",
	docker = "",
	gcp = "",
	helm = "󱂈",
	kubernetes = "󱃾",
	netlify = "󰚩",
	terraform = "󱁢",
	vercel = "󰚩",
}

-- Icons for Debug Adapter Protocol (DAP)
icons.dap = {
	breakpoint = "",
	breakpoint_condition = "",
	breakpoint_disabled = "",
	breakpoint_log = "󰛿",
	breakpoint_rejected = "",
	bug = "",
	call_stack = "",
	continue = "",
	debug = "",
	disconnect = "",
	loaded_sources = "",
	log_point = ".>",
	pause = "",
	repl = "",
	restart = "",
	scopes = "󰘧",
	start = "",
	step_back = "",
	step_into = "",
	step_out = "",
	step_over = "",
	status = "",
	stop = "",
	stopped = "󰁕",
	terminate = "󰝤",
	watches = "󰩣",
}

-- Icons for LSP diagnostics
icons.diagnostics = {
	debug = "",
	deprecated = "󰷈",
	diagnostic = "󰒡",
	error = "",
	hint = "",
	info = "",
	note = "󰎞",
	off = "󰝦",
	ok = "",
	todo = "󰄱",
	trace = "",
	warn = "",
}

-- Icons for various text editors
icons.editors = {
	emacs = "",
	helix = "",
	neovim = "",
	vim = "",
	vscode = "",
	zed = "󰙀",
}

-- Icons for file operations and types
icons.files = {
	explorer = "󰙅",
	export = "",
	file = "",
	file_added = "󰝒",
	file_modified = "󰷉",
	file_removed = "󰝓",
	folder = "",
	folder_added = "󰝖",
	folder_empty = "",
	folder_empty_open = "",
	folder_open = "",
	folder_removed = "󰝗",
	grep = "",
	modified = "󰷈",
	move = "󰆏",
	new_file = "󰝒",
	normal = "󰈔",
	pdf = "",
	recent_files = "",
	readonly = "󰌾",
	rename = "󰑕",
	save = "󰆓",
	share = "",
	symlink = "",
	symlink_dir = "",
}

-- Icons for Git and version control
icons.git = {
	added = "󰐖",
	blame_line = "󰋼",
	branch = "",
	cherry_pick = "",
	clean = "",
	commit = "󰜘",
	compare = "",
	conflict = "",
	copied = "",
	diff_this = "",
	fork = "",
	fugitive = "",
	git = "",
	gitsigns = "",
	ignored = "◌",
	lazygit = "󰊤",
	log = "󰌌",
	merge = "",
	modified = "󰏬",
	pull = "",
	pull_request = "",
	push = "",
	rebase = "",
	remote = "",
	removed = "󰐐",
	renamed = "",
	reset_hunk = "",
	revert = "",
	stage_hunk = "",
	staged = "󰄬",
	status = "󰒡",
	stash = "󰆓",
	tag = "",
	unstaged = "󰜺",
	untracked = "󰘓",
	worktree = "",
}

-- Icons for code 'kinds' (used in completion and symbols)
icons.kind = {
	class = "󰠱",
	color = "󰏘",
	constant = "󰏿",
	constructor = "",
	enum = "",
	enum_member = "",
	event = "",
	field = "󰇽",
	file = "󰈙",
	folder = "󰉋",
	func = "󰊕",
	function_ = "󰊕",
	interface = "",
	keyword = "󰌋",
	method = "󰆧",
	module = "󰏓",
	namespace = "󰌗",
	null = "",
	number = "",
	object = "",
	operator = "󰆕",
	package = "󰏖",
	property = "󰜢",
	reference = "󰈇",
	snippet = "",
	string = "󰉿",
	struct = "󰙅",
	template = "",
	text = "󰉿",
	type_parameter = "",
	unit = "",
	value = "󰎠",
	variable = "󰂡",
}

-- Icons for programming languages
icons.languages = {
	angular = "",
	bash = "",
	c = "",
	config = "",
	cpp = "",
	csharp = "󰧱",
	css = "",
	deno = "",
	dockerfile = "",
	env = "",
	go = "",
	graphql = "",
	html = "",
	java = "",
	javascript = "",
	json = "",
	kotlin = "",
	lock = "󰌾",
	lua = "",
	markdown = "",
	mysql = "",
	node = "",
	php = "",
	postgres = "",
	python = "",
	react = "",
	redis = "",
	ruby = "",
	rust = "",
	sql = "",
	sqlite = "",
	svelte = "",
	swift = "",
	tailwind = "󱏿",
	tex = "ﭨ",
	toml = "",
	typescript = "",
	vim = "",
	vue = "",
	yaml = "",
}

-- Icons for LSP features
icons.lsp = {
	action = "󰆹",
	base = "",
	code_action = "󰌵",
	code_lens = "󰄄",
	declaration = "󰳿",
	definition = "󰳽",
	diagnostic = "󰒡",
	error = "",
	formatting = "",
	hint = "",
	hover = "󰙴",
	implementation = "󰡱",
	info = "",
	inlay_hint = "󰩫",
	logo = "",
	lsp = "",
	references = "󰈇",
	rename = "󰑕",
	signature = "󰞋",
	status = "󰔷",
	symbols = "󰀬",
	type_definition = "",
	warn = "",
	workspace = "󰙅",
}

-- Miscellaneous icons
icons.misc = {
	squirrel = "",
}

-- Icons for navigation and UI elements
icons.nav = {
	arrow_collapsed = "",
	arrow_down = "",
	arrow_left = "",
	arrow_right = "",
	arrow_up = "",
	bold_divider_left = "",
	bold_divider_right = "",
	breadcrumb = "»",
	chevron_down = "",
	chevron_left = "",
	chevron_right = "",
	chevron_up = "",
	divider_left = "",
	divider_right = "",
	dots = "󰇘",
	ellipsis = "…",
	history_back = "󰔶",
	history_forward = "󰔷",
	home = "",
	prompt = "",
	separator = "➜",
	vertical_bar = "│",
}

-- Icons for network-related status
icons.network = {
	antenna = "󰠠",
	bluetooth = "󰂯",
	cloud = "",
	connection = "󰖂",
	download = "",
	ethernet = "󰀂",
	firewall = "󰗹",
	globe = "",
	ip = "",
	lan = "󰩠",
	modem = "󰈀",
	server = "󰘬",
	upload = "",
	wifi = "",
}

-- Icons for operating systems
icons.os = {
	alpine = "",
	android = "",
	arch = "",
	centos = "",
	debian = "",
	fedora = "",
	freebsd = "",
	gentoo = "",
	ios = "",
	linux = "",
	macos = "",
	manjaro = "",
	mint = "",
	netbsd = "󰈹",
	nixos = "",
	openbsd = "󰈺",
	opensuse = "",
	raspbian = "",
	redhat = "",
	ubuntu = "",
	windows = "",
}

-- Icons for buffer tabs
icons.tabs = {
	tab = "󰓩",
	tab_close = "󰅖",
	tab_close_all = "󰅙",
	tab_fresh = "󰈙",
	tab_modified = "●",
	tab_new = "󰓪",
	tab_next = "󰓱",
	tab_pin = "",
	tab_previous = "󰓯",
	tab_unpin = "",
}

-- Icons for testing frameworks
icons.testing = {
	beaker = "",
	coverage = "󰠠",
	debug = "",
	fail = "󰅚",
	mock = "󰙔",
	pass = "",
	skip = "󰈉",
	test = "󰙨",
	watch = "󰥔",
}

-- Icons for time and calendar
icons.time = {
	alarm = "󰀠",
	calendar = "",
	clock = "",
	date = "",
	schedule = "󰸗",
	stopwatch = "󰔡",
	timer = "󰔛",
	timer_end = "󰔟",
	timer_stop = "󰔝",
}

-- General user interface icons
icons.ui = {
	bold_line_left = "▎",
	bolt = "",
	bookmark = "",
	bug = "",
	check = "",
	circle = "",
	clipboard = "",
	clipboard_text = "󰅌",
	close = "",
	comment = "",
	copy = "",
	cut = "",
	dashboard = "",
	dedent = "",
	delete = "",
	diff = "╱",
	eob = " ",
	error_circle = "",
	filter = "󰈲",
	float = "",
	fold = " ",
	foldclose = "",
	foldopen = "",
	foldsep = " ",
	fullscreen = "󰊓",
	indent = "",
	info = "",
	info_circle = "",
	keyboard = "󰌌",
	lightbulb = "",
	line = "┆",
	loading = "󰑈",
	lock = "",
	maximize = "⛶",
	minimize = "‾",
	outdent = "",
	paste = "",
	pin = "󰐃",
	play = "",
	quit = "",
	refresh = "",
	reload = "",
	run = "󰜈",
	search = "",
	settings = "",
	sort = "󰒿",
	stop = "",
	success_circle = "",
	text = "󰉿",
	toggle_off = "",
	toggle_on = "",
	undo = "",
	unlock = "",
	unpin = "󰐄",
	visibility_off = "",
	visibility_on = "",
	warning = "",
	warning_circle = "",
	whitespace = "󰌒",
	window = "",
	wrench = "",
	command = "",
	history = "",
}

-- Icons for vendors and brands
icons.vendors = {
	amazon = "",
	apple = "",
	brew = "",
	cargo = "󰘚",
	discord = "󰙯",
	fzf = "󰉋",
	github = "",
	gitlab = "",
	google = "",
	jest = "󰙨",
	lazy = "󰒲",
	linkedin = "",
	microsoft = "",
	npm = "",
	pip = "󰅩",
	pnpm = "",
	poetry = "󰏗",
	ripgrep = "󰱽",
	slack = "",
	telescope = "",
	twitter_x = "󰕸",
	vitest = "󰙩",
	yarn = "",
	youtube = "",
}

-- Return the complete icons table to be used by 'require'
return icons
